# Exemple de meta.yaml
package:
  name: gsql
  version: "0.1.1"  # Assurez-vous que la version correspond à votre tag

source:
  url: https://pypi.io/packages/source/g/gsql/gsql-$TAG_VERSION.tar.gz

build:
  number: 3

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/gopu-inc/gsql
  license: MIT
  summary: 
