{% set name = "gsql" %}
{% set version = "3.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..  # Utilise le code source local depuis le répertoire parent

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - gsql = gsql.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  
  run:
    - python >=3.8
    - click >=8.0.0
    - colorama >=0.4.4
    - prompt-toolkit >=3.0.0
    - rich >=13.0.0
    - pandas >=1.3.0
    - numpy >=1.21.0
    - nltk >=3.6.0
    - spacy >=3.5.0
    - psutil >=5.9.0
    - typing-extensions >=4.7.0
    - cryptography >=41.0.0
    - sqlalchemy >=2.0.0
    - sqlite

test:
  imports:
    - gsql
    - gsql.database
  commands:
    - python -c "import gsql; print(f'GSQL version: {gsql.__version__}')"
    - gsql --help
    - gsql --version
  requires:
    - pip
  source_files:
    - tests/
    - test/

about:
  home: https://github.com/gopu-inc/gsql
  license: MIT
  license_file: LICENSE
  summary: Complete SQL Database System in Python with AI Integration
  description: |
    GSQL is a comprehensive SQL database system built in Python featuring
    AI-powered query optimization, natural language processing for SQL queries,
    advanced analytics, and seamless integration with modern data workflows.
    
    Key Features:
    - AI-enhanced SQL query optimization
    - Natural language to SQL conversion
    - Built-in machine learning capabilities
    - Multi-database support
    - REST API and CLI interfaces
    - Docker and Kubernetes ready
  doc_url: https://github.com/gopu-inc/gsql/wiki
  dev_url: https://github.com/gopu-inc/gsql

extra:
  recipe-maintainers:
    - ceoseshell
    - gopu-inc
