# Exemple de meta.yaml
package:
  name: gsql
  version: "3.0.2"  # Assurez-vous que la version correspond à votre tag

source:
  url: https://pypi.io/packages/source/g/gsql/gsql-{{ version }}.tar.gz  # Ou .whl

build:
  number: 46

requirements:
  host:
    - python
    - pip
  run:
    - python

about:
  home: https://github.com/gopu-inc/gsql
  license: MIT
  summary: 
