package:
  name: gsql
  version: 3.1.0  # Directement ici

source:
  path: ..

build:
  number: 1
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - click >=8.0.0
    - colorama >=0.4.4
    - pandas >=1.3.0
    - numpy >=1.21.0
    - nltk >=3.6.0

about:
  home: https://github.com/gopu-inc/gsql
  license: MIT
  summary: Complete SQL Database System in Python with AI Integration
